#!/usr/bin/env bash
# Computer use for agents on a Mac: cua-driver (desktop apps) + agent-browser (web pages),
# optionally with the "Agent Chrome" (the agents' own visible Chrome on CDP port 9333).
# Same setup as aibo-mac. Idempotent: re-run any time; it fixes what's missing and leaves
# the rest alone. See README.md for what each step does and what stays manual.
#
#   ./install.sh                  cua-driver + its daemon, agent-browser, skills, MCP wiring
#   ./install.sh --agent-chrome   also the Agent Chrome LaunchAgent + agent-browser cdp config
#   ./install.sh --check          only report what's installed (changes nothing)
set -euo pipefail

AGENT_CHROME=0; CHECK=0
for a in "$@"; do
  case "$a" in
    --agent-chrome) AGENT_CHROME=1 ;;
    --check) CHECK=1 ;;
    -h|--help) sed -n 2,10p "$0"; exit 0 ;;
    *) echo "unknown option: $a"; exit 1 ;;
  esac
done

[ "$(uname -s)" = "Darwin" ] || { echo "macOS only for now (see README: Linux)"; exit 1; }

UID_=$(id -u)
BIN="$HOME/.local/bin/cua-driver"
CUA_APP="/Applications/CuaDriver.app/Contents/MacOS/cua-driver"
CUA_PLIST="$HOME/Library/LaunchAgents/com.trycua.cua-driver.plist"
CHROME="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
CHROME_DIR="$HOME/Library/Application Support/Google/Chrome-Agent"
CHROME_PLIST="$HOME/Library/LaunchAgents/com.sandesh.agent-chrome.plist"
CDP_PORT=9333
AB_SKILL=""   # set once agent-browser is installed

ok()   { printf '  \033[32m✓\033[0m %s\n' "$*"; }
miss() { printf '  \033[33m•\033[0m %s\n' "$*"; }
step() { printf '\n== %s ==\n' "$*"; }
loaded() { launchctl print "gui/$UID_/$1" >/dev/null 2>&1; }

# Link a skill folder into every agent skills dir that exists, never replacing a real folder.
link_skill() {
  local name=$1 src=$2 d
  for d in "$HOME/.claude/skills" "$HOME/.config/opencode/skills" "$HOME/.agents/skills"; do
    [ -d "$(dirname "$d")" ] || continue
    mkdir -p "$d"
    if [ -e "$d/$name" ] || [ -L "$d/$name" ]; then ok "skill $name already in $d"
    else ln -s "$src" "$d/$name"; ok "linked skill $name into $d"; fi
  done
}

check() {
  step "status"
  if [ -x "$CUA_APP" ]; then ok "cua-driver $("$CUA_APP" --version 2>/dev/null | awk '{print $2}')"; else miss "cua-driver not installed"; fi
  if loaded com.trycua.cua-driver; then ok "cua-driver daemon running (com.trycua.cua-driver)"; else miss "cua-driver daemon not loaded"; fi
  [ -x "$CUA_APP" ] && "$CUA_APP" permissions status 2>/dev/null | sed 's/^/    /' || true
  if command -v agent-browser >/dev/null; then ok "$(agent-browser --version)"; else miss "agent-browser not installed"; fi
  if command -v claude >/dev/null && claude mcp list 2>/dev/null | grep -q '^cua-driver'; then ok "Claude Code MCP: cua-driver"; else miss "Claude Code MCP: cua-driver not registered"; fi
  if grep -q '"cua-driver"' "$HOME/.config/opencode/opencode.jsonc" "$HOME/.config/opencode/opencode.json" 2>/dev/null; then ok "OpenCode MCP: cua-driver"; else miss "OpenCode MCP: cua-driver not configured"; fi
  if loaded com.sandesh.agent-chrome; then ok "Agent Chrome LaunchAgent loaded"; else miss "Agent Chrome not set up (optional: --agent-chrome)"; fi
  if curl -fsS "http://127.0.0.1:$CDP_PORT/json/version" >/dev/null 2>&1; then ok "CDP answering on :$CDP_PORT"; else miss "nothing on CDP :$CDP_PORT"; fi
}

if [ $CHECK = 1 ]; then check; exit 0; fi

# ---------------------------------------------------------------- cua-driver
step "cua-driver (desktop apps)"
if [ -x "$CUA_APP" ]; then
  ok "installed: $("$CUA_APP" --version | awk '{print $2}') (update later with: cua-driver update --apply)"
else
  # The vendor's installer: puts CuaDriver.app in /Applications (stable bundle id
  # com.trycua.driver, so macOS permissions stick across updates) and a wrapper in ~/.local/bin.
  curl -fsSL https://cua.ai/driver/install.sh | bash
fi
[ -x "$BIN" ] || { mkdir -p "$(dirname "$BIN")"; ln -sf "$CUA_APP" "$BIN"; }

# The daemon. The installer doesn't register one on macOS; without it, permission checks
# are attributed to whichever terminal launched the tool. KeepAlive so it survives reboots.
cat > "$CUA_PLIST" <<PL
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>Label</key><string>com.trycua.cua-driver</string>
  <!-- Generated by agent-tools/computer-use/install.sh. -->
  <key>ProgramArguments</key><array>
    <string>$CUA_APP</string>
    <string>serve</string>
    <string>--grant</string>
    <string>existing-profile</string>
    <string>--allow-legacy-existing-profile-approval</string>
  </array>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>ThrottleInterval</key><integer>5</integer>
  <key>StandardOutPath</key><string>/tmp/cua-driver.log</string>
  <key>StandardErrorPath</key><string>/tmp/cua-driver.log</string>
</dict></plist>
PL
if loaded com.trycua.cua-driver; then
  launchctl kickstart -k "gui/$UID_/com.trycua.cua-driver"; ok "daemon restarted"
else
  launchctl bootstrap "gui/$UID_" "$CUA_PLIST"; ok "daemon started"
fi

# Skill pack: the vendor links it into every agent it detects (Claude Code, OpenCode, Codex…).
"$CUA_APP" skills install >/dev/null 2>&1 && ok "cua-driver skill linked into detected agents" || miss "cua-driver skills install failed (run it by hand)"

# ------------------------------------------------------------- agent-browser
step "agent-browser (web pages)"
if command -v agent-browser >/dev/null; then
  ok "installed: $(agent-browser --version) (update: npm i -g agent-browser)"
else
  command -v npm >/dev/null || { echo "npm required: brew install node"; exit 1; }
  npm install -g agent-browser
fi
AB_SKILL="$(npm root -g)/agent-browser/skills/agent-browser"
[ -d "$AB_SKILL" ] && link_skill agent-browser "$AB_SKILL" || miss "agent-browser skill folder not found in the npm package"

# ---------------------------------------------------------------- MCP wiring
# cua-driver is an MCP server; agent-browser is a CLI the skill teaches, so it needs no MCP.
step "MCP: cua-driver for Claude Code and OpenCode"
if command -v claude >/dev/null; then
  if claude mcp list 2>/dev/null | grep -q '^cua-driver'; then ok "Claude Code already has it"
  else claude mcp add --scope user cua-driver -- "$BIN" mcp && ok "added to Claude Code (user scope)"; fi
else miss "Claude Code not installed; later: claude mcp add --scope user cua-driver -- $BIN mcp"; fi

OC="$HOME/.config/opencode/opencode.jsonc"; [ -f "$OC" ] || OC="$HOME/.config/opencode/opencode.json"
if [ -d "$HOME/.config/opencode" ]; then
  python3 - "$OC" "$BIN" <<'PY'
import json, os, sys
path, binp = sys.argv[1], sys.argv[2]
raw = open(path).read() if os.path.exists(path) else '{"$schema": "https://opencode.ai/config.json"}'
try:
    cfg = json.loads(raw)
except ValueError:  # has comments: don't rewrite a hand-edited file
    print(f"  • {path} has comments; add under \"mcp\": \"cua-driver\": {{\"type\": \"local\", \"command\": [\"{binp}\", \"mcp\"]}}")
    sys.exit(0)
mcp = cfg.setdefault("mcp", {})
if "cua-driver" in mcp:
    print("  ✓ OpenCode already has it")
else:
    mcp["cua-driver"] = {"type": "local", "command": [binp, "mcp"]}
    open(path, "w").write(json.dumps(cfg, indent=2) + "\n")
    print(f"  ✓ added to OpenCode ({path})")
PY
else miss "OpenCode not installed; skipped"; fi

# -------------------------------------------------------------- Agent Chrome
if [ $AGENT_CHROME = 1 ]; then
  step "Agent Chrome (own profile, CDP :$CDP_PORT)"
  [ -x "$CHROME" ] || { echo "Google Chrome not found in /Applications"; exit 1; }
  mkdir -p "$CHROME_DIR"
  cat > "$CHROME_PLIST" <<PL
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>Label</key><string>com.sandesh.agent-chrome</string>
  <!-- Generated by agent-tools/computer-use/install.sh. The agents' own visible Chrome:
       a separate user-data-dir, so Chrome allows a fixed debugging port with no
       "Allow remote debugging?" prompt. The user's own Chrome is untouched. -->
  <key>ProgramArguments</key><array>
    <string>$CHROME</string>
    <string>--user-data-dir=$CHROME_DIR</string>
    <string>--remote-debugging-port=$CDP_PORT</string>
    <string>--no-first-run</string>
    <string>--no-default-browser-check</string>
  </array>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>ThrottleInterval</key><integer>30</integer>
</dict></plist>
PL
  if loaded com.sandesh.agent-chrome; then ok "already running (not restarted, so open tabs survive)"
  else launchctl bootstrap "gui/$UID_" "$CHROME_PLIST"; ok "started"; fi

  # agent-browser's default session attaches to this Chrome instead of launching its own.
  mkdir -p "$HOME/.agent-browser"
  python3 - "$HOME/.agent-browser/config.json" "$CDP_PORT" <<'PY'
import json, os, sys
p, port = sys.argv[1], sys.argv[2]
cfg = json.load(open(p)) if os.path.exists(p) else {}
if cfg.get("cdp") == port:
    print(f"  ✓ agent-browser already points at :{port}")
else:
    cfg["cdp"] = port
    json.dump(cfg, open(p, "w"))
    print(f"  ✓ agent-browser now attaches to :{port} ({p})")
PY

  # 1Password: a custom user-data-dir doesn't see the main Chrome's native-messaging host,
  # so without this link the extension asks for a separate sign-in instead of using the app.
  NMH_SRC="$HOME/Library/Application Support/Google/Chrome/NativeMessagingHosts/com.1password.1password.json"
  NMH_DST="$CHROME_DIR/NativeMessagingHosts/com.1password.1password.json"
  if [ -f "$NMH_SRC" ]; then
    mkdir -p "$(dirname "$NMH_DST")"; ln -sf "$NMH_SRC" "$NMH_DST"; ok "1Password extension will talk to the desktop app"
  else miss "1Password not set up in the main Chrome; skip or re-run after installing it"; fi
else
  # Without an Agent Chrome, agent-browser launches its own Chrome for Testing.
  step "agent-browser browser"
  agent-browser install >/dev/null 2>&1 && ok "Chrome for Testing installed" || miss "agent-browser install failed (run it by hand)"
fi

check

cat <<'TXT'

== Still manual (once per machine) ==
  1. Grant macOS permissions to CuaDriver (Accessibility, Screen Recording):
       cua-driver permissions grant
     Click Allow in the dialogs; it verifies live capture at the end.
  2. With --agent-chrome: in the new Chrome window, sign in to Google, install the
     1Password extension, and log in to the sites routines need.
  3. Restart Claude Code / OpenCode so they pick up the MCP server and skills.
TXT
